name: "balance-transfer"
x-type: "hlfv1"
description: "Balance Transfer Network"
version: "1.0"
channels:
  atguiguchannel:
    orderers:
      - orderer.atguigu.com
    peers:
      peer0.org1.atguigu.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org1.atguigu.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.org2.atguigu.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org2.atguigu.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

    chaincodes:
      - atguigubalancetransfer:v0

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.atguigu.com
      - peer1.org1.atguigu.com
    certificateAuthorities:
      - ca-org1
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/org1.atguigu.com/users/Admin@org1.atguigu.com/msp/keystore/5890f0061619c06fb29dea8cb304edecc020fe63f41a6db109f1e227cc1cb2a8_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/org1.atguigu.com/users/Admin@org1.atguigu.com/msp/signcerts/Admin@org1.atguigu.com-cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.atguigu.com
      - peer1.org2.atguigu.com
    certificateAuthorities:
      - ca-org2
    adminPrivateKey:
      path: artifacts/channel/crypto-config/peerOrganizations/org2.atguigu.com/users/Admin@org2.atguigu.com/msp/keystore/1995b11d6573ed3be52fcd7a5fa477bc0f183e1f5f398c8281d0ce7c2c75a076_sk
    signedCert:
      path: artifacts/channel/crypto-config/peerOrganizations/org2.atguigu.com/users/Admin@org2.atguigu.com/msp/signcerts/Admin@org2.atguigu.com-cert.pem

orderers:
  orderer.atguigu.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.atguigu.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/ordererOrganizations/atguigu.com/orderers/orderer.atguigu.com/tls/ca.crt

peers:
  peer0.org1.atguigu.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.atguigu.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/org1.atguigu.com/peers/peer0.org1.atguigu.com/tls/ca.crt

  peer1.org1.atguigu.com:
    url: grpcs://localhost:7056
    grpcOptions:
      ssl-target-name-override: peer1.org1.atguigu.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/org1.atguigu.com/peers/peer1.org1.atguigu.com/tls/ca.crt

  peer0.org2.atguigu.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer0.org2.atguigu.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/org2.atguigu.com/peers/peer0.org2.atguigu.com/tls/ca.crt

  peer1.org2.atguigu.com:
    url: grpcs://localhost:8056
    eventUrl: grpcs://localhost:8058
    grpcOptions:
      ssl-target-name-override: peer1.org2.atguigu.com
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/org2.atguigu.com/peers/peer1.org2.atguigu.com/tls/ca.crt

certificateAuthorities:
  ca-org1:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/org1.atguigu.com/ca/ca.org1.atguigu.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca-org1

  ca-org2:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/channel/crypto-config/peerOrganizations/org2.atguigu.com/ca/ca.org2.atguigu.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca-org2
